---
- name: Install System Software
  hosts: windows
  gather_facts: false
  tasks:
    - name: Install required software
      chocolatey.chocolatey.win_chocolatey:
        name:
          - 7zip
        state: present
