---
- name: Install System Software
  hosts: windows
  vars:
    choco_packages:
      - name: nodejs
        version: 13.0.0
      - name: python
        version: 3.6.0
      - name: firefox
        version: 121.0.0

  tasks:
   - name: Install specific versions of packages sequentially
     chocolatey.chocolatey.win_chocolatey:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      force: yes
     loop: "{{ choco_packages }}"

   - name: Check python version
     ansible.windows.win_command: python --version
     register: check_python_version

   - name: Print version
     ansible.builtin.debug:
      msg: "{{ check_python_version }}"
