---
- name: Coleta de Propriedades do Sistema
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Coletar fatos do Ansible
      ansible.builtin.setup:

    - name: Coletar informações sobre os serviços
      ansible.builtin.service_facts:

    - name: Inicializar lista de serviços habilitados e em execução
      set_fact:
        active_enabled_services: []

    - name: Inicializar lista de serviços em execução mas desabilitados
      set_fact:
        active_disabled_services: []

    - name: Coletar serviços habilitados e em execução
      set_fact:
        active_enabled_services: "{{ active_enabled_services + [item.key] }}"
      when: item.value.state == 'running' and item.value.status == 'enabled'
      with_dict: "{{ ansible_facts.services }}"

    - name: Coletar serviços em execução mas desabilitados
      set_fact:
        active_disabled_services: "{{ active_disabled_services + [item.key] }}"
      when: item.value.state == 'running' and item.value.status == 'disabled'
      with_dict: "{{ ansible_facts.services }}"

    - name: Definir fatos personalizados com informações do sistema
      set_fact:
        system_info: |
          Informações do Sistema:
          - Nome do Host: {{ ansible_facts.hostname }}
          - Sistema Operacional: {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}
          - Release do Sistema: {{ ansible_facts.distribution_release }}
          - Release do Kernel: {{ ansible_facts.kernel }}
          - CPUs: {{ ansible_facts.processor_vcpus }}
          - RAM: {{ ansible_facts.memtotal_mb }} MB
          - Armazenamento: {{ ansible_facts.mounts[0].size_total | human_readable }}
          - Arquitetura: {{ ansible_facts.architecture }}
          - Endereços IPv4: {{ ansible_facts.all_ipv4_addresses | join(', ') }}
          - DNS: {{ ansible_facts.dns.nameservers | join(', ') }}
          - Hora do Sistema: {{ ansible_facts.date_time.iso8601 }}
          - Fuso Horário: {{ ansible_facts.date_time.tz }}
          - Uptime: {{ (ansible_facts.uptime_seconds // 3600) | int }} horas, {{ ((ansible_facts.uptime_seconds % 3600) // 60) | int }} minutos, {{ (ansible_facts.uptime_seconds % 60) | int }} segundos
          - Serviços Ativos e Habilitados: {{ active_enabled_services | join(', ') }}
          - Serviços Ativos e Desabilitados: {{ active_disabled_services | join(', ') }}
          - Processos: 
            {% for process in ansible_facts.ansible_local.proccess_status_check.localfacts.top_processes | from_json %}
            - {{ process }}
            {% endfor %}

    - name: Exibir Informações do Sistema
      ansible.builtin.debug:
        msg: "{{ system_info }}"
