---
- name: Coleta de Propriedades do Sistema
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Coletar fatos do Ansible
      ansible.builtin.setup:

    - name: Exibir Informações do Sistema
      ansible.builtin.debug:
        msg: |
          Informações do Sistema:
          - Nome do Host: {{ ansible_facts['hostname'] }}
          - Sistema Operacional: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}
          - Release do Sistema: {{ ansible_facts['distribution_release'] }}
          - Release do Kernel: {{ ansible_facts['kernel'] }}
          - CPUs: {{ ansible_facts['processor_vcpus'] }}
          - RAM: {{ ansible_facts['memtotal_mb'] }} MB
          - Armazenamento: {{ ansible_facts['mounts'][0]['size_total'] | human_readable }}
          - Arquitetura: {{ ansible_facts['architecture'] }}
          - Endereços IPv4: {{ ansible_facts['all_ipv4_addresses'] | join(', ') }}
          - DNS: {{ ansible_facts['dns']['nameservers'] | join(', ') }}
          - Hora do Sistema: {{ ansible_facts['date_time']['iso8601'] }}
          - Fuso Horário: {{ ansible_facts['date_time']['tz'] }}
          - Uptime: {{ (ansible_facts['uptime_seconds'] | int | float | round(0, 'floor') / 3600) | int }} horas, {{ ((ansible_facts['uptime_seconds'] | int | float | round(0, 'floor') % 3600) / 60) | int }} minutos, {{ (ansible_facts['uptime_seconds'] | int | float | round(0, 'floor') % 60) | int }} segundos
          - Serviços Ativos: {{ ansible_facts['ansible_local']['services_status_check']['localfacts']['active_enabled_services'] | join(', ') }}
          - Processos: {{ ansible_facts['ansible_local']['proccess_status_check']['localfacts']['top_processes'] | join(', ') }}
